### ISSUE TITLE
the value of u_mouse changes when mouse click even if the mouse does not move

### ISSUE THREAD

**Issue by zhao-huang** [actarian/glsl-canvas#10]
When using glsl-canvas, a mouse click will change the value of u_mouse.x even if the mouse does not move. I tested the same shader code on the [patriciogonzalezvivo/glslCanvas](https://github.com/patriciogonzalezvivo/glslCanvas), its value is stable. 

``` glsl
#ifdef GL_ES
precision mediump float;
#endif

uniform vec2 u_resolution;
uniform vec2 u_mouse;

void main() {
    gl_FragColor = vec4(vec3(u_mouse.x/u_resolution.x),1.0);
}
```

**Comment by actarian** [comment]
Hi @zhao-huang the value of u_mouse changes in glsl-canvas on these DOM events: MouseDown, MouseMove, TouchStart and TouchMove.

**Comment by zhao-huang** [comment]
Hello, @actarian . Thank you for your reply.
Sorry, I did not describe the problem clearly. I think the behavior of the click event may have a minor problem.

Reproduce the behavior:
step 1. Use the above shader code.
step 2. Move the mouse cursor to any point in the canvas and stop it.
step 3. Keep the cursor in the same position and click the mouse.

Expected behavior:
In step 2 above, the color of the canvas is from `vec3(u_mouse.x/u_resolution.x)`, so this will be a grayscale color related to the horizontal position of the mouse cursor.
In step 3, because the cursor does not move when the mouse is clicked, u_mouse.x should be kept at the same value, and the canvas should be kept at the same grayscale color.

Behaviors that occur:
However, step 3 will change the value of u_mouse.x due to the mouse click event. On my device, u_mouse.x always increased by 8 when clicked. This only occurs when the cursor is in the canvas range. Clicks outside the canvas range will not cause this behavior.

This is the code I use to test this behavior:
https://codepen.io/zhao-huang/pen/XWNVEJJ

**Comment by actarian** [comment]
@zhao-huang  I see, there are incorrect u_mouse values setted on MouseDown event. I'll fix it on next release. Thank You.

**Comment by zhao-huang** [comment]
@actarian
It works properly now.
Thank you.
