### ISSUE TITLE
Pinpointed Safari `SyntaxError: Invalid regular expression: invalid group specifier name` error to this package

### ISSUE THREAD

**Issue by iolyd** [actarian/glsl-canvas#17]
I'm using this package in an Angular project and have had reports that the application does not display in Safari (macOS). I've had a lot of trouble pinpointing the potential source of the problem since safari's log is so bare (`SyntaxError: Invalid regular expression: invalid group specifier name`), but after testing myself and playing with disabling/enabling imports and features, I've come to identify this package as the source, but I'm having trouble establishing a more precise diagnotic.

Our project only uses the `Canvas` class and one or two calls of `setUniform(...)`

I'm not knowledgeable on the subject of regular expressions, but a quick read highlighted that lookahead and lookbehind assertions aren't yet supported by Safari and I suspect I found some occurrences.

Is this an expected behaviour that was already identified (limited support on safari)?

**Comment by actarian** [comment]
@emmbema Thank You! Issue has been resolved on last release `0.2.5`
