### ISSUE TITLE
Crashes on browsers not supporting WebGL2

### ISSUE THREAD

**Issue by dtinth** [actarian/glsl-canvas#2]
This is Safari 13.0.2 (15608.2.30.1.1)

![image](https://user-images.githubusercontent.com/193136/67569585-75157000-f759-11e9-8752-fb25ca500e81.png)

```
ReferenceError: Can't find variable: WebGL2RenderingContext
```

## Workaround

It is now fixed. Upgrade to 0.1.6.

```html
<script src="https://unpkg.com/glsl-canvas-js@0.1.6/dist/glsl-canvas.min.js"></script>
```

~~If you don’t use WebGL2, version 0.1.3 is available.~~

```html
<script src="https://unpkg.com/glsl-canvas-js@0.1.3/dist/glsl-canvas.min.js"></script>
```

**Comment by actarian** [comment]
@dtinth issue has been fixed in latest release. thank you!

**Comment by dtinth** [comment]
Confirmed fixed, thank you so much!
