### ISSUE TITLE
#include causing undeclared identifier error

### ISSUE THREAD

**Issue by wyhinton** [actarian/glsl-canvas#21]
Hello,

Steps to reproduce:
- Clone the repo
- F1->Show glslCanvas
- Open ```example-11-include-02.glsl```

Gives Error:
```ERROR line 2 rx undeclared identifier```
VSCode screenshot:
![image](https://user-images.githubusercontent.com/38958118/123491893-e9b34880-d5e5-11eb-9034-f2e4adce08d7.png)

However ```example-11.glsl```, which also uses ```#include```,  works as expected. 

The only changes to my glsl-canvas settings are:
```
  "glsl-canvas.textures": {
    "0": "./texture.jpg",
    "1": "https://rawgit.com/actarian/plausible-brdf-shader/master/textures/noise/cloud-1.png",
    "2": "https://rawgit.com/actarian/plausible-brdf-shader/master/textures/noise/cloud-2.jpg"
  },
  "glsl-canvas.extensions": [],
```

OS: Win10

**Comment by XertroV** [comment]
I have the same issue.

**Comment by wyhinton** [comment]
@XertroV So example-11-include-02.glsl + example-11.glsl both compile fine for you?  What's your OS?

**Comment by XertroV** [comment]
@wyhinton yes, though you need example-11-include-01.glsl and example-11-include-03.glsl present also.

in my case there was an issue with importing things that had declarations like `precision mediump float` or the like. basically b/c of incorrect order of things in the final glsl file that gets generated. it's a bit of a pain b/c the error msgs aren't great, there's no debug log AFAIK, and you have to guess a bit at what's going on to fix those sorts of issues.

my os is win10
