### ISSUE TITLE
Document check causes reference error

### ISSUE THREAD

**Issue by astrovpls** [actarian/glsl-canvas#28]
Hello,

Faced an issue when using with next.js: ReferenceError: document is not defined
https://github.com/actarian/glsl-canvas/blob/585d6866cbb1e90ed219272ca9e9247ddc1566a7/src/glsl.ts#L34-L38

Seems like `if (document)` check is not working as expected.
`if (typeof window === 'object')` solved an issue.

**Comment by actarian** [comment]
@astrovpls PR has been merged and published as 0.2.9. Thank you!.
