### ISSUE TITLE
Buggy buffers

### ISSUE THREAD

**Issue by valler** [actarian/glsl-canvas#3]
I've problems figuring out what exactly is needed to make buffers work.
The provided examples work fine (e.g. https://raw.githubusercontent.com/actarian/glsl-canvas/master/docs/shaders/example-21.glsl) However when I try to strip them down, things stop working very quickly.

Below is a minimal example of what I thought should work: Writing into a buffer, reading from it and displaying the result on screen. The canvas stays transparent instead of showing red.

Any help is very appreciated. Thanks!

```
#version 300 es

precision highp float;

uniform vec2 u_resolution;
uniform sampler2D u_buffer0;

out vec4 color;

void main()
{
#ifdef BUFFER_0
	color = vec4(1,0,0,1);
#else
	vec2 uv = gl_FragCoord.xy/u_resolution;
	color = texture(u_buffer0, uv);
#endif
}

```

**Comment by valler** [comment]
The next example works. Note that the string "u_time" has to appear twice to make this work - anywhere.

```
#version 300 es

precision highp float;

uniform vec2 u_resolution;
uniform sampler2D u_buffer0;

out vec4 color;

void main()
{
#ifdef BUFFER_0
	color = vec4(1,0,0,1);
#else
	vec2  uv = gl_FragCoord.xy/u_resolution;
	color = texture(u_buffer0, uv);
#endif
}

//u_timeu_time
```

**Comment by valler** [comment]
This (and similar code) breaks:

```
#version 300 es

precision highp float;

uniform vec2 u_resolution;
uniform sampler2D u_buffer0;

out vec4 color;

void main()
{
#ifdef BUFFER_0
#include "buffer0.glsl"
#else
	vec2 uv = gl_FragCoord.xy/u_resolution;
	color = texture(u_buffer0, uv);
#endif
}
//u_timeu_time
```

This works (having one "u_time" inside the conditional):
```
#version 300 es

precision highp float;

uniform vec2 u_resolution;
uniform sampler2D u_buffer0;

out vec4 color;

void main()
{
#ifdef BUFFER_0
//u_time
#include "buffer0.glsl"
#else
	vec2 uv = gl_FragCoord.xy/u_resolution;
	color = texture(u_buffer0, uv);
#endif
}
//u_time
```

**Comment by actarian** [comment]
Hi @valler it seems there is a problem switching from WebGL to WebGL2 context, opening directly this code in vscode-glsl-canvas that use glsl-canvas does work

```
#version 300 es

precision highp float;

uniform vec2 u_resolution;
uniform sampler2D u_buffer0;

out vec4 color;

void main() {
    
    #if defined(BUFFER_0)
    color = vec4(1.0, 0.0, 0.0, 1.0);
    
    #else
    vec2 uv = gl_FragCoord.xy / u_resolution.xy;
    color = texture(u_buffer0, uv);
    
    #endif
    
}
```

in which way are you passing the fragment shader?

**Comment by valler** [comment]
I'm using the data uri method.
Can't confirm that the code is running in vs code whithout the `//u_time` hack:
<img width="1370" alt="Screenshot 2019-11-25 at 17 05 59" src="https://user-images.githubusercontent.com/2582817/69556977-0f114800-0fa6-11ea-889e-a645512b649c.png">
<img width="1382" alt="Screenshot 2019-11-25 at 17 06 18" src="https://user-images.githubusercontent.com/2582817/69556978-0f114800-0fa6-11ea-81e8-375135ca8f31.png">

**Comment by valler** [comment]
It seems `u_time` is not always `0.0` on frame one. Which makes the previous solution unreliable as well.
Either one has to make sure `u_time` deterministically starts with a well defined value (e.g. 0.0), or another uniform like `u_frame` which behaves this way is needed. Actually having both uniforms with well defined behaviour would be great.

**Comment by actarian** [comment]
@valler Fyi, u_time influence the rendering loop. If you set u_time you got a loop, if not only one frame will be rendered. u_time value corresponds to timer seconds / 1000.0 so it could start from values different than zero.
```
const hasTime = (fragmentString.match(/u_time/g) || []).length > 1;
this.animated = hasTime || hasDate || hasMouse;
this.uniforms.create(UniformMethod.Uniform1f, UniformType.Float, 'u_time', [timer.current / 1000.0]);
```

**Comment by valler** [comment]
This explains alot.
Do you have any suggestion then on how to initialize the first frame of a buffer reliably? Currently I'm waiting for an arbitrary amount of time, say 0.1s, before I start to read/sample from buffers.  This technique obviously relies on performance. I'd rather prefer a solution which guarantees a buffer has been initialized. Is this something which should be fixed, or should I implement my own solution ontop?

Very much appreciate your help! Thanks @actarian :)

**Comment by actarian** [comment]
@valler I will debug the `data-fragment-url` activation method, but the u_time hack shouldn't be necessary, I think there is a problem with the initialization of the webgl context, if a WebGL context has been initialized on a canvas it cannot be initialized to WebGL2 context without before creating a new canvas. I'll let you know.

**Comment by actarian** [comment]
@valler sorry for the late reply, I've verified that there's nothing wrong with the code, buffers are rendered correctly in the first frame, and their output are available as input on the next frame.   

On first frame their value is always a `vec4(0,0,0,0); ` For this reason what you consider an hack is the correct behaviour, setting `u_time` create a loop needed for the buffer to be rendered and passed to the next frame.
