### ISSUE TITLE
problems with passing options and/or setting properties when using in a VueJS component (glsl-canvas + VueJS)

### ISSUE THREAD

**Issue by mm4ry** [actarian/glsl-canvas#7]
I really like this library, so I would like to stick to it, however, I can't get to pass Canvas `options` and set Canvas properties when using VueJS. I want to change the size of the rendering, since it automatically sets the `Canvas` width and height to clientWidth and clientHight, which is too heavy for the purpose.

None of the shown options and property value's in the Safari Canvas inspector can be changed.
<img width="730" alt="Screenshot 2020-09-21 at 18 32 17" src="https://user-images.githubusercontent.com/14110539/93794945-0ecef100-fc39-11ea-98f8-a10bb4e2d287.png">

In my template, I build a canvas:
`    <canvas
      id="glslcc"
    ></canvas>`

Then I install the module via NPM and import it like this:
`import { Canvas } from 'glsl-canvas-js';`

The GLSL code and image texture are stored in the VueJS Component `data` function and work perfectly fine.

In the `mounted` cycle, I call the `runWebGL()` method, to make sure all HTML elements are ready.

```  
mounted() {
    this.runWebGL();
  },
```

In `runWebGL()` I create a glsl `Canvas object `and pass the `Canvas options`. 

```
    runWebGL(){
      let VueThis = this;

      let glslOptions = {
        alpha: false,
        antialias: false,
        width: 10,
        height: 10,
        W: 10,
        H: 10,
        contextMode: "flat",
        preserveDrawingBuffer: false,
      };

      VueThis.canvasElement = document.getElementById('glslcc');
      VueThis.glsl = new Canvas(VueThis.canvasElement, glslOptions); // options do not work
      VueThis.glsl.setUniform('u_tex0', VueThis.textureImage ); // this works
      VueThis.glsl.load(VueThis.shader); // this works

      VueThis.glsl.W = 10; // setting the Canvas properties does not work
      VueThis.glsl.H = 10; / setting the Canvas properties does not work
      VueThis.glsl.width = 10; // setting the Canvas properties does not work
      VueThis.glsl.height = 10; / setting the Canvas properties does not work
      
    }
```

I am aware that in this case I don't need to use a VueThis variable, but since I had been trying to make this work for a long while, I wanted to be sure I didn't make a mistake.

When I change the attribute `width` and `height` in the `<canvas>` html element and the page hot-reloads, it DOES work. But I can't reproduce this behaviour with the VueJS lifecycles.

I only have -some- years of experience, so I hope I am not bothering you with a beginners' mistake.

**Comment by actarian** [comment]
Hi @mm4ry there's no width and height options on glsl-canvas, the size of the canvas is inherited from the canvas element that in this case is `VueThis.canvasElement = document.getElementById('glslcc');`, so you only need to style properly your canvasElement or apply the style properties dynamically eg. `VueThis.canvasElement.style.width = '10px'; VueThis.canvasElement.style.height= '10px';`  

Instead the options of glsl-canvas extends the `WebGLContextAttributes` and adds some custom options:  
```
export interface ICanvasOptions extends WebGLContextAttributes {  
	vertexString?: string;  
	fragmentString?: string;  
	backgroundColor?: string;  
	workpath?: string;  
	onError?: Function;  
	extensions?: string[];  
	mode?: ContextMode;  
	mesh?: string;  
	doubleSided?: boolean;  
}  
```

**Comment by mm4ry** [comment]
Thank you for your reply. 

Let me explain the case: when I used GlslShader.js before, in a simple HTML page without a framework, I could use `width` and `height` parameters for the rendering, but give a different size to the `<canvas>`. I would like to have the canvas fullscreen size, but the rendering on 800x800 pixels for example, otherwise it will be too much memory.

`<canvas class="glslCanvas" data-fragment-url="shader.glsl" data-textures="shader_img/SpiritandForm_2020.jpg" width="800" height="800" style="width:100%;height:100%;"></canvas>`

But when I import the library via NPM and create the canvas dynamically, I can't find a comparable way to do this. In the docs there seems to be a W and H for the Glsl Canvas object. When I dynamically set these, it applies. But the WebGL object is already in the size it inherited from the canvas, so this is too late.

```
VueThis.glsl.W = 10;
VueThis.glsl.H = 10;
```
This would all be perfect if these options (just like `antialias` and the others) would come through by creating a `new Canvas`, but for any reason they don't.

Would you know if there is another way to have the size of the rendering different from the size of the html `canvas` object?

**Comment by actarian** [comment]
@mm4ry ok, this is not possible right now because glsl-canvas-js check the canvas element size to obtain properly width and height parameters, I should introduce a new options parameter to handle this particular case.

**Comment by actarian** [comment]
@mm4ry the only thing you can do is set the `devicePixelRatio` property to a value like 0.5 (half resolution) and force a resize:
```
VueThis.glsl.devicePixelRatio = 0.5;
VueThis.glsl.width = Math.ceil(VueThis.glsl.width * 0.5);
VueThis.glsl.height = Math.ceil(VueThis.glsl.height * 0.5);
```

**Comment by mm4ry** [comment]
@actarian thank you! I did not think of this solution. 
I appreciate the possibilities of the library a lot, so I am happy to experiment with this small hack to make it work.
